# File used by Conda (if you use it)
# to install the necessary dependencies for the project.

name: opencv-examples

channels:
  - defaults

dependencies:
  - python=>3.0
  - pip
  - pip:
    - opencv-python
